name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @foundation-ui/components install && pnpm --filter @foundation-ui/core install && @foundation-ui/tokens install
      - run: pnpm --filter @foundation-ui/components build && pnpm --filter @foundation-ui/core build && @foundation-ui/tokens build
      - run: pnpm --filter @foundation-ui/components test && pnpm --filter @foundation-ui/core test && @foundation-ui/tokens test
