name: Publish Packages
on:
  push:
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@foundation-ui"

      - name: Install dependencies
        run: pnpm install

      - name: Publish packages
        run: pnpm publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
